openapi: 3.0.3
info:
  title: Shop Products APIs Definition
  description: |
     Using this OpenAPI specification, any consumer can understand the APIs that are exposed by Shop
  termsOfService: https://shop.com/terms/
  contact:
    name: API Support
    url: https://www.shop.com/support
    email: support@shop.com
  license:
    name: Shop License
    url: https://www.shop.com/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: https://development.shop-server.com/v1
    description: Development server
  - url: https://staging.shop-server.com/v1
    description: Staging server
  - url: https://api.shop-server.com/v1
    description: Production server
  - url: https://{username}.server.com:{port}/{version}
    variables:
      username:
        default: demo
        description: This value is assigned by the service provider.
      port:
        enum:
          - "8443"
          - "443"
        default: "8443"
      version:
        default: v1
paths: {}